### PR TITLE
jsdom-react: click -  Also trigger mouseUp/mouseDown

### LINKED ISSUE #32: `click` in react adapter should also emit mouseDown and mouseUp events
use case: a component listens to `mouseDown` and not `click. In react the tests that use `click` will fail but in other adapters it won't
this is because in real browsers, when you click, you get both click events and mouse events.

thus, I think that `click` in the react adapter should also emit `mouseUp` and `mouseDown` events

### PR DESCRIPTION
**Pull request by hepiyellow**
Resolves #32

### CODE REVIEW

File: adapters/jsdom-react/src/spec.tsx [hunk 1]
```diff
@@ -30,35 +30,67 @@ describe('react base driver - test suite', () => {
...
-		const elem = document.createElement('div');
-		document.body.appendChild(elem);
-		const btn = <button onClick={s}>bob</button>;
-		ReactDOM.render(btn, elem);
+		it('sends event data properly on simulated events when element is attached to body', async () => {
+			const cleanJsdom = require('jsdom-global')();
+			const s = spy();
+			const elem = document.createElement('div');
+			document.body.appendChild(elem);
+			const btn = <button onClick={s}>bob</button>;
```
Comment (borisd9) [inline adapters/jsdom-react/src/spec.tsx]: I think all this rendering part would be better hidden behind some `renderAndMount` function. We can reveal one from the `testKit`

**Comment by hepiyellow** [comment]
I like react-testing-library
It has a simple render/cleanup api

**Comment by borisd9** [comment]
@hepiyellow  have you checked the build?
